# Generated by Django 4.2.7 on 2023-12-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0006_alter_userrequest_enquiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="file",
            field=models.FileField(unique=True, upload_to="media/"),
        ),
    ]
