# Generated by Django 5.1.1 on 2024-09-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UnitTopic",
        ),
    ]
