# Generated by Django 4.2.7 on 2023-12-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_description_userrequest_enquiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='enquiry',
            field=models.TextField(blank=True),
        ),
    ]
